### PR TITLE
Aggiornamento Certificato

### PR DESCRIPTION
**Pull request by exbyte**
Ciao ho fatto uno script update_certificate.sh per aggiornare in modo automatico il certificato ogni mese

#!/bin/sh
certbot renew --standalone
docker cp /etc/letsencrypt/live/meet.esperto-informatico.it/  mm_mm_1:certs

da posizionare in /etc/cron.monthly

### CODE REVIEW

**Comment by misi** [comment]
Sorry I speak only Hungarian and English. Can you please split changes and describe issues.

**Comment by misi** [comment]
@exbyte @tapionx can you please help me to split this Pull Request to more focused smaller PR-s.
I can't really merge it this way. 
I really want to help you and incorporate any change, but please let's do it one by one.

**Comment by tapionx** [comment]
@misi i think this PR was created by mistake, you can close it.
It was about automatic certbot renewal, but in my opinion it's up to the system administrator to handle that, not everyone will use Let's Encrypt.

**Comment by misi** [comment]
@tapionx I will close it. Many thanks for your fast reply. 
Let me know if I need to change anything to use other CA-s..
My choice let's encrypt was because it is general free CA and a good first start that could work if instance has internet access. Thanks again..

**Pull request closed without merging**
